pub const KG_TO_G: u32 = 1000;

pub const CHARACTER_NAME_MIN_LEN: usize = 4;
pub const CHARACTER_NAME_MAX_LEN: usize = 32;

pub const DEFAULT_CHARACTER_LEVEL: u16 = 1;
pub const DEFAULT_CHARACTER_EXPERIENCE: u64 = 0;
pub const DEFAULT_CHARACTER_HEALTH: u32 = 120;
pub const DEFAULT_CHARACTER_MANA: u32 = 60;
pub const DEFAULT_CHARACTER_CAPACITY: u32 = 15 * KG_TO_G;
pub const DEFAULT_CHARACTER_SPEED: u16 = 120;
pub const DEFAULT_CHARACTER_ATTACK_SPEED: u16 = 100;

pub const DEFAULT_SPAWN_X: u16 = 0;
pub const DEFAULT_SPAWN_Y: u16 = 0;

pub const MAP_VIEW_RADIUS: u16 = 32;

pub const SECTOR_SIZE: u16 = 256;

pub const MOVEMENT_COOLDOWN_FACTOR: u64 = 40_000;
pub const MOVEMENT_INTENTION_WINDOW_MS: u64 = 25;

pub const CHAT_MESSAGE_MIN_LEN: usize = 1;
pub const CHAT_MESSAGE_MAX_LEN: usize = 1024;
pub const CHAT_BUBBLE_BASE_DURATION_MS: u64 = 3000;
pub const CHAT_BUBBLE_MS_PER_CHAR: u64 = 100;

pub const MAX_OPEN_CONTAINERS: usize = 32;
pub const MAX_FLOOR_ITEMS_PER_TILE: usize = 100;
pub const ADJACENCY_RANGE: u16 = 1;
pub const ACTION_COOLDOWN_MS: u64 = 200;
