// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateCharacterV1Reducer from "../create_character_v_1_reducer";
import SayV1Reducer from "../say_v_1_reducer";
import SelectCharacterV1Reducer from "../select_character_v_1_reducer";
import UnselectCharacterV1Reducer from "../unselect_character_v_1_reducer";

export type CreateCharacterV1Params = __Infer<typeof CreateCharacterV1Reducer>;
export type SayV1Params = __Infer<typeof SayV1Reducer>;
export type SelectCharacterV1Params = __Infer<typeof SelectCharacterV1Reducer>;
export type UnselectCharacterV1Params = __Infer<typeof UnselectCharacterV1Reducer>;

