// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bubbleId: __t.u64().primaryKey().name("bubble_id"),
  characterName: __t.string().name("character_name"),
  characterLevel: __t.u16().name("character_level"),
  content: __t.string(),
  x: __t.u16(),
  y: __t.u16(),
  sentAt: __t.timestamp().name("sent_at"),
});
