// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatBubbleV1 = __t.object("ChatBubbleV1", {
  bubbleId: __t.u64(),
  userId: __t.identity(),
  content: __t.string(),
  x: __t.u16(),
  y: __t.u16(),
  sentAt: __t.timestamp(),
});
export type ChatBubbleV1 = __Infer<typeof ChatBubbleV1>;

// The tagged union or sum type for the algebraic type `DeferredEventV1`.
export const DeferredEventV1 = __t.enum("DeferredEventV1", {
  SignedOut: __t.identity(),
});
export type DeferredEventV1 = __Infer<typeof DeferredEventV1>;

export const OccupiedTileV1 = __t.object("OccupiedTileV1", {
  tileId: __t.u64(),
  sectorKey: __t.u64(),
  userId: __t.identity(),
});
export type OccupiedTileV1 = __Infer<typeof OccupiedTileV1>;

export const OneshotDeferredEventV1 = __t.object("OneshotDeferredEventV1", {
  jobId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  get event() {
    return DeferredEventV1;
  },
  sender: __t.identity(),
  createdAt: __t.timestamp(),
});
export type OneshotDeferredEventV1 = __Infer<typeof OneshotDeferredEventV1>;

export const UserPositionV1 = __t.object("UserPositionV1", {
  userId: __t.identity(),
  x: __t.u16(),
  y: __t.u16(),
});
export type UserPositionV1 = __Infer<typeof UserPositionV1>;

export const UserV1 = __t.object("UserV1", {
  userId: __t.identity(),
  createdAt: __t.timestamp(),
  lastActiveAt: __t.timestamp(),
});
export type UserV1 = __Infer<typeof UserV1>;

