// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  characterId: __t.u64().name("character_id"),
  userId: __t.identity().name("user_id"),
  level: __t.u16(),
  experience: __t.u64(),
  health: __t.u32(),
  mana: __t.u32(),
  capacity: __t.u32(),
  freeCapacity: __t.u32().name("free_capacity"),
  speed: __t.u16(),
  attackSpeed: __t.u16().name("attack_speed"),
});
