// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RaceV1,
  ClassV1,
  GenderV1,
} from "./types";


export default __t.row({
  characterId: __t.u64().name("character_id"),
  userId: __t.identity().name("user_id"),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  get race() {
    return RaceV1;
  },
  get class() {
    return ClassV1;
  },
  get gender() {
    return GenderV1;
  },
  createdAt: __t.timestamp().name("created_at"),
});
